language: java

jdk:
  - openjdk14

sudo: false

branches:
  only:
    - master

env:
  global:
    - CODECOV_TOKEN="04572a2f-b4e2-4530-9a51-250c60665fa8"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -s595659@mail.ru
    on_success: never # default: change
    on_failure: always # default: always